### ISSUE TITLE
Wrong number of arguments passed to FastSpringException

### ISSUE THREAD

**Issue by john2x** [artlogicmedia/fastspring#2]
`FastSpringException`'s constructor takes 3 arguments, but it is called with 4 arguments in the code.

```python
raise FastSpringException('Could not get order information', status, message, reason)
```

**Comment by artlogicmedialtd** [comment]
Dear John Louis Del Rosario,

We have absolutely no idea what this message means. 

Please can you explain it? If there was an error, what was the URL, what parameters or arguments were sent? I hope you can help.


Best wishes,


David

_______________________________________________________
David Hooper - Director - Artlogic Media Ltd.
t: 0845 838 1588  /  + 44 (0) 20 7627 0774
f: 020 8497 6555 skype: artlogicmedia
e: david.hooper@artlogic.net  w: http://www.artlogic.net  
Postal address: 83 Leathwaite Road, London SW11 6RN
Office address: 28 Old Town, London SW4 0LB
_______________________________________________________

To find out more about our sensational app for iPad visit https://privateviews.com

**Comment by john2x** [comment]
Hi. Sorry for not being clear, but it seems it's fixed now :+1:

**Comment by ghost** [comment]
Hi John,

Thanks for your input. 

Do you work for Fastspring? I don't know who you are!!

Thanks anyway.

David
